Frontends/App.Movie.WebUI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace App.Movie.WebUI.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Frontends/App.Movie.WebUI/Controllers/MovieController.cs
using App.Movie.Dto.Dtos.MovieDtos;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Threading.Tasks;

namespace App.Movie.WebUI.Controllers
{
    public class MovieController : Controller
    {
        private readonly IHttpClientFactory _httpClientFactory;

        public MovieController(IHttpClientFactory httpClientFactory)
        {
            _httpClientFactory = httpClientFactory;
        }

        public IActionResult Index()
        {
            ViewBag.v1= "Film Listesi";
            ViewBag.v2 = "Ana Sayfa";
            ViewBag.v3 = "Tüm Filmler";
            return View();
        }
        public async Task<IActionResult> MovieDetail(int id)
        {
            ViewBag.PageHero = true;
            id = 0;
            return View();
        }
    }
}

Frontends/App.Movie.WebUI/ViewComponents/MovieDetailRelatedViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace App.Movie.WebUI.ViewComponents
{
    public class MovieDetailRelatedViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

Frontends/App.Movie.WebUI/ViewComponents/MovieDetailShareSocialMediaViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace App.Movie.WebUI.ViewComponents
{
    public class MovieDetailShareSocialMediaViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

Frontends/App.Movie.WebUI/ViewComponents/MovieImageAndWatchTrailerViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace App.Movie.WebUI.ViewComponents
{
    public class MovieImageAndWatchTrailerViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

Frontends/App.Movie.WebUI/ViewComponents/MovieListViewComponent.cs
using App.Movie.Dto.Dtos.MovieDtos;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace App.Movie.WebUI.ViewComponents
{
    public class MovieListViewComponent : ViewComponent
    {
        private readonly IHttpClientFactory _httpClientFactory;

        public MovieListViewComponent(IHttpClientFactory httpClientFactory)
        {
            _httpClientFactory = httpClientFactory;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var client = _httpClientFactory.CreateClient();
            var responseMessage = await client.GetAsync("https://localhost:7050/list");

            if (responseMessage.IsSuccessStatusCode)
            {
                var jsonData = await responseMessage.Content.ReadAsStringAsync();
                var values = JsonConvert.DeserializeObject<List<ResultMovieDto>>(jsonData);
                return View(values);
            }
            return View();
        }
    }
}

Frontends/App.Movie.WebUI/ViewComponents/MovieOverviewViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace App.Movie.WebUI.ViewComponents
{
    public class MovieOverviewViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

Frontends/App.Movie.WebUI/ViewComponents/MovieRateViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace App.Movie.WebUI.ViewComponents
{
    public class MovieRateViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

Frontends/App.Movie.WebUI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

Frontends/App.Movie.WebUI/Views/Movie/Index.cshtml
@{
    ViewData["Title"] = "MovieList";
}

<div class="page-single movie_list">
	<div class="container">
		<div class="row ipad-width2">
			<div class="col-md-8 col-sm-12 col-xs-12">
				<div class="topbar-filter">
					<p>Toplam <span>1,608 </span> Film Mevcut</p>
					<label>Sıralama:</label>
					<select>
						<option value="popularity">Popüler Sıralama A--Z</option>
						<option value="popularity">Popüler Sıralama Z--A</option>
						<option value="rating">Imdb Puanına Göre Artan</option>
						<option value="rating">Imdb Puanına Göre Azalan</option>
						<option value="date">Tarihe Göre Artan</option>
						<option value="date">Tarihe Göre Azalan</option>
					</select>
					<a href="movielist.html" class="list"><i class="ion-ios-list-outline active"></i></a>
					<a href="moviegrid.html" class="grid"><i class="ion-grid"></i></a>
				</div>

				<vc:movie-list />

				<div class="topbar-filter">
					<label>Movies per page:</label>
					<select>
						<option value="range">5 Movies</option>
						<option value="saab">10 Movies</option>
					</select>
					<div class="pagination2">
						<span>Page 1 of 2:</span>
						<a class="active" href="#">1</a>
						<a href="#">2</a>
						<a href="#"><i class="ion-arrow-right-b"></i></a>
					</div>
				</div>
			</div>

			<div class="col-md-4 col-sm-12 col-xs-12">
				<div class="sidebar">
					<div class="searh-form">
						<h4 class="sb-title">Film Arama</h4>
						<form class="form-style-1" action="#">
							<div class="row">
								<div class="col-md-12 form-it">
									<label>Film Adı</label>
									<input type="text" placeholder="Kelime Girin">
								</div>
								<div class="col-md-12 form-it">
									<label>Film Türü</label>
									<div class="group-ip">
										<select>
											<option value="">Film Türü Seçiniz</option>
											<option value="Action1">Aksiyon</option>
											<option value="Action2">Macera</option>
											<option value="Action3">Animasyon</option>
											<option value="Action4">Korku</option>
											<option value="Action5">Komedi</option>
										</select>
									</div>
								</div>
								<div class="col-md-12 form-it">
									<label>Imdb Puanı</label>
									<select>
										<option value="range">Imdb Puanı Seçiniz</option>
										<option value="saab">8 ve üzeri</option>
										<option value="saab">6 ve 8 arası</option>
										<option value="saab">4 ve 6 arası</option>
										<option value="saab">4'ten düşük</option>
									</select>
								</div>
								<div class="col-md-12 form-it">
									<label>Çıkış Tarihi</label>
									<div class="row">
										<div class="col-md-6">
											<select>
												<option value="range">Yıl Seçiniz</option>
												<option value="number">2000</option>
												<option value="number">2010</option>
												<option value="number">2020</option>
											</select>
										</div>
										<div class="col-md-6">
											<select>
												<option value="range">Yıl Seçiniz</option>
												<option value="number">2000</option>
												<option value="number">2010</option>
												<option value="number">2020</option>
											</select>
										</div>
									</div>
								</div>
								<div class="col-md-12 ">
									<input class="submit" type="submit" value="Film Ara">
								</div>
							</div>
						</form>
					</div>
					<div class="ads">
						<img src="/theme/images/uploads/ads1.png" alt="">
					</div>
					<div class="sb-facebook sb-it">
						<h4 class="sb-title">Find us on Facebook</h4>
						<iframe src="#" data-src="https://www.facebook.com/plugins/page.php?href=https%3A%2F%2Fwww.facebook.com%2Ftemplatespoint.net%2F%3Ffref%3Dts&tabs=timeline&width=340&height=315px&small_header=true&adapt_container_width=false&hide_cover=false&show_facepile=true&appId" height="315" style="width:100%;border:none;overflow:hidden"></iframe>
					</div>
					<div class="sb-twitter sb-it">
						<h4 class="sb-title">Tweet to us</h4>
						<div class="slick-tw">
							<div class="tweet item" id="">
							</div>
							<div class="tweet item" id="">
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

Frontends/App.Movie.WebUI/Views/Shared/Components/MovieDetailRelated/Default.cshtml
<div id="moviesrelated" class="tab">
	<div class="row">
		<h3>Benzer Filmler</h3>
		<h2>Skyfall: Quantum of Spectre</h2>
		<div class="topbar-filter">
			<p>Found <span>12 movies</span> in total</p>
			<label>Sort by:</label>
			<select>
				<option value="popularity">Popularity Descending</option>
				<option value="popularity">Popularity Ascending</option>
				<option value="rating">Rating Descending</option>
				<option value="rating">Rating Ascending</option>
				<option value="date">Release date Descending</option>
				<option value="date">Release date Ascending</option>
			</select>
		</div>
		<div class="movie-item-style-2">
			<img src="/theme/images/uploads/mv1.jpg" alt="">
			<div class="mv-item-infor">
				<h6><a href="#">oblivion <span>(2012)</span></a></h6>
				<p class="rate"><i class="ion-android-star"></i><span>8.1</span> /10</p>
				<p class="describe">Earth's mightiest heroes must come together and learn to fight as a team if they are to stop the mischievous Loki and his alien army from enslaving humanity...</p>
				<p class="run-time"> Run Time: 2h21’    .     <span>MMPA: PG-13 </span>    .     <span>Release: 1 May 2015</span></p>
				<p>Director: <a href="#">Joss Whedon</a></p>
				<p>Stars: <a href="#">Robert Downey Jr.,</a> <a href="#">Chris Evans,</a> <a href="#">  Chris Hemsworth</a></p>
			</div>
		</div>
		<div class="movie-item-style-2">
			<img src="/theme/images/uploads/mv2.jpg" alt="">
			<div class="mv-item-infor">
				<h6><a href="#">into the wild <span>(2014)</span></a></h6>
				<p class="rate"><i class="ion-android-star"></i><span>7.8</span> /10</p>
				<p class="describe">As Steve Rogers struggles to embrace his role in the modern world, he teams up with a fellow Avenger and S.H.I.E.L.D agent, Black Widow, to battle a new threat...</p>
				<p class="run-time"> Run Time: 2h21’    .     <span>MMPA: PG-13 </span>    .     <span>Release: 1 May 2015</span></p>
				<p>Director: <a href="#">Anthony Russo,</a><a href="#">Joe Russo</a></p>
				<p>Stars: <a href="#">Chris Evans,</a> <a href="#">Samuel L. Jackson,</a> <a href="#">  Scarlett Johansson</a></p>
			</div>
		</div>
		<div class="movie-item-style-2">
			<img src="/theme/images/uploads/mv3.jpg" alt="">
			<div class="mv-item-infor">
				<h6><a href="#">blade runner  <span>(2015)</span></a></h6>
				<p class="rate"><i class="ion-android-star"></i><span>7.3</span> /10</p>
				<p class="describe">Armed with a super-suit with the astonishing ability to shrink in scale but increase in strength, cat burglar Scott Lang must embrace his inner hero and help...</p>
				<p class="run-time"> Run Time: 2h21’    .     <span>MMPA: PG-13 </span>    .     <span>Release: 1 May 2015</span></p>
				<p>Director: <a href="#">Peyton Reed</a></p>
				<p>Stars: <a href="#">Paul Rudd,</a> <a href="#"> Michael Douglas</a></p>
			</div>
		</div>
		<div class="movie-item-style-2">
			<img src="/theme/images/uploads/mv4.jpg" alt="">
			<div class="mv-item-infor">
				<h6><a href="#">Mulholland pride<span> (2013)  </span></a></h6>
				<p class="rate"><i class="ion-android-star"></i><span>7.2</span> /10</p>
				<p class="describe">When Tony Stark's world is torn apart by a formidable terrorist called the Mandarin, he starts an odyssey of rebuilding and retribution.</p>
				<p class="run-time"> Run Time: 2h21’    .     <span>MMPA: PG-13 </span>    .     <span>Release: 1 May 2015</span></p>
				<p>Director: <a href="#">Shane Black</a></p>
				<p>Stars: <a href="#">Robert Downey Jr., </a> <a href="#">  Guy Pearce,</a><a href="#">Don Cheadle</a></p>
			</div>
		</div>
		<div class="movie-item-style-2">
			<img src="/theme/images/uploads/mv5.jpg" alt="">
			<div class="mv-item-infor">
				<h6><a href="#">skyfall: evil of boss<span> (2013)  </span></a></h6>
				<p class="rate"><i class="ion-android-star"></i><span>7.0</span> /10</p>
				<p class="describe">When Tony Stark's world is torn apart by a formidable terrorist called the Mandarin, he starts an odyssey of rebuilding and retribution.</p>
				<p class="run-time"> Run Time: 2h21’    .     <span>MMPA: PG-13 </span>    .     <span>Release: 1 May 2015</span></p>
				<p>Director: <a href="#">Alan Taylor</a></p>
				<p>Stars: <a href="#">Chris Hemsworth,  </a> <a href="#">  Natalie Portman,</a><a href="#">Tom Hiddleston</a></p>
			</div>
		</div>
		<div class="topbar-filter">
			<label>Movies per page:</label>
			<select>
				<option value="range">5 Movies</option>
				<option value="saab">10 Movies</option>
			</select>
			<div class="pagination2">
				<span>Page 1 of 2:</span>
				<a class="active" href="#">1</a>
				<a href="#">2</a>
				<a href="#"><i class="ion-arrow-right-b"></i></a>
			</div>
		</div>
	</div>
</div>

Frontends/App.Movie.WebUI/Views/Shared/Components/MovieDetailShareSocialMedia/Default.cshtml
<div class="social-btn">
	<a href="#" class="parent-btn"><i class="ion-heart"></i> Favorilerine Ekle</a>
	<div class="hover-bnt">
		<a href="#" class="parent-btn"><i class="ion-android-share-alt"></i>Paylaş</a>
		<div class="hvr-item">
			<a href="#" class="hvr-grow"><i class="ion-social-facebook"></i></a>
			<a href="#" class="hvr-grow"><i class="ion-social-twitter"></i></a>
			<a href="#" class="hvr-grow"><i class="ion-social-instagram"></i></a>
			<a href="#" class="hvr-grow"><i class="ion-social-youtube"></i></a>
		</div>
	</div>
</div>

Frontends/App.Movie.WebUI/Views/Shared/Components/MovieImageAndWatchTrailer/Default.cshtml
<div class="col-md-4 col-sm-12 col-xs-12">
	<div class="movie-img sticky-sb">
		<img src="/theme/images/uploads/movie-single.jpg" alt="">
		<div class="movie-btn">
			<div class="btn-transform transform-vertical red">
				<div><a href="#" class="item item-1 redbtn"> <i class="ion-play"></i> Fragmanı İzle</a></div>
				<div><a href="https://www.youtube.com/embed/o-0hcF97wy0" class="item item-2 redbtn fancybox-media hvr-grow"><i class="ion-play"></i></a></div>
			</div>
			<div class="btn-transform transform-vertical">
				<div><a href="#" class="item item-1 yellowbtn"> <i class="ion-card"></i> Sepete Ekle</a></div>
				<div><a href="#" class="item item-2 yellowbtn"><i class="ion-card"></i></a></div>
			</div>
		</div>
	</div>
</div>

Frontends/App.Movie.WebUI/Views/Shared/Components/MovieList/Default.cshtml
@using App.Movie.Dto.Dtos.MovieDtos
@model List<ResultMovieDto>

@foreach (var item in Model)
{
	<div class="movie-item-style-2">
		<img src="@item.CoverImageUrl" alt="">
		<div class="mv-item-infor">
			<h6><a href="moviesingle.html">@item.Title <span>(@item.CreatedYear)</span></a></h6>
			<p class="rate"><i class="ion-android-star"></i><span>@item.Rating</span> /10</p>
			<p class="describe">@item.Description</p>
			<p class="run-time"> Run Time: @item.Duration Dk’    .     <span>MMPA: PG-13 </span>    .     <span>Release: @item.ReleaseDate</span></p>
			<p>Director: <a href="#">Joss Whedon</a></p>
			<p>Stars: <a href="#">Robert Downey Jr.,</a> <a href="#">Chris Evans,</a> <a href="#">  Chris Hemsworth</a></p>
		</div>
	</div>
}

Frontends/App.Movie.WebUI/Views/Shared/Components/MovieOverview/Default.cshtml
<div id="overview" class="tab active">
	<div class="row">
		<div class="col-md-8 col-sm-12 col-xs-12">
			<p>Tony Stark creates the Ultron Program to protect the world, but when the peacekeeping program becomes hostile, The Avengers go into action to try and defeat a virtually impossible enemy together. Earth's mightiest heroes must come together once again to protect the world from global extinction.</p>
			<div class="title-hd-sm">
				<h4>Fotoğraf Ve Videolar</h4>
				<a href="#" class="time">5 Video & 26 Fotoğraf <i class="ion-ios-arrow-right"></i></a>
			</div>
			<div class="mvsingle-item ov-item">
				<a class="img-lightbox" data-fancybox-group="gallery" href="images/uploads/image11.jpg"><img src="/theme/images/uploads/image1.jpg" alt=""></a>
				<a class="img-lightbox" data-fancybox-group="gallery" href="images/uploads/image21.jpg"><img src="/theme/images/uploads/image2.jpg" alt=""></a>
				<a class="img-lightbox" data-fancybox-group="gallery" href="images/uploads/image31.jpg"><img src="/theme/images/uploads/image3.jpg" alt=""></a>
				<div class="vd-it">
					<img class="vd-img" src="/theme/images/uploads/image4.jpg" alt="">
					<a class="fancybox-media hvr-grow" href="https://www.youtube.com/embed/o-0hcF97wy0"><img src="/theme/images/uploads/play-vd.png" alt=""></a>
				</div>
			</div>
			<div class="title-hd-sm">
				<h4>Oyuncular</h4>
				<a href="#" class="time">Tüm Oyuncular  <i class="ion-ios-arrow-right"></i></a>
			</div>
			<div class="mvcast-item">
				<div class="cast-it">
					<div class="cast-left">
						<img src="/theme/images/uploads/cast1.jpg" alt="">
						<a href="#">Robert Downey Jr.</a>
					</div>
					<p>...  Robert Downey Jr.</p>
				</div>
				<div class="cast-it">
					<div class="cast-left">
						<img src="/theme/images/uploads/cast2.jpg" alt="">
						<a href="#">Chris Hemsworth</a>
					</div>
					<p>...  Thor</p>
				</div>
				<div class="cast-it">
					<div class="cast-left">
						<img src="/theme/images/uploads/cast3.jpg" alt="">
						<a href="#">Mark Ruffalo</a>
					</div>
					<p>...  Bruce Banner/ Hulk</p>
				</div>
				<div class="cast-it">
					<div class="cast-left">
						<img src="/theme/images/uploads/cast4.jpg" alt="">
						<a href="#">Chris Evans</a>
					</div>
					<p>...  Steve Rogers/ Captain America</p>
				</div>
				<div class="cast-it">
					<div class="cast-left">
						<img src="/theme/images/uploads/cast5.jpg" alt="">
						<a href="#">Scarlett Johansson</a>
					</div>
					<p>...  Natasha Romanoff/ Black Widow</p>
				</div>
				<div class="cast-it">
					<div class="cast-left">
						<img src="/theme/images/uploads/cast6.jpg" alt="">
						<a href="#">Jeremy Renner</a>
					</div>
					<p>...  Clint Barton/ Hawkeye</p>
				</div>
				<div class="cast-it">
					<div class="cast-left">
						<img src="/theme/images/uploads/cast7.jpg" alt="">
						<a href="#">James Spader</a>
					</div>
					<p>...  Ultron</p>
				</div>
				<div class="cast-it">
					<div class="cast-left">
						<img src="/theme/images/uploads/cast9.jpg" alt="">
						<a href="#">Don Cheadle</a>
					</div>
					<p>...  James Rhodes/ War Machine</p>
				</div>
			</div>
			<div class="title-hd-sm">
				<h4>User reviews</h4>
				<a href="#" class="time">Tüm Yorumları Gör (56) <i class="ion-ios-arrow-right"></i></a>
			</div>
			<!-- movie user review -->
			<div class="mv-user-review-item">
				<h3>Yapılan Son Değerlendirme</h3>
				<div class="no-star">
					<i class="ion-android-star"></i>
					<i class="ion-android-star"></i>
					<i class="ion-android-star"></i>
					<i class="ion-android-star"></i>
					<i class="ion-android-star"></i>
					<i class="ion-android-star"></i>
					<i class="ion-android-star"></i>
					<i class="ion-android-star"></i>
					<i class="ion-android-star"></i>
					<i class="ion-android-star last"></i>
				</div>
				<p class="time">
					28 Nisan 2025 <a href="#"> Ali Yıldız</a>
				</p>
				<p>This is by far one of my favorite movies from the MCU. The introduction of new Characters both good and bad also makes the movie more exciting. giving the characters more of a back story can also help audiences relate more to different characters better, and it connects a bond between the audience and actors or characters. Having seen the movie three times does not bother me here as it is as thrilling and exciting every time I am watching it. In other words, the movie is by far better than previous movies (and I do love everything Marvel), the plotting is splendid (they really do out do themselves in each film, there are no problems watching it more than once.</p>
			</div>
		</div>
		<div class="col-md-4 col-xs-12 col-sm-12">
			<div class="sb-it">
				<h6>Yönetmen: </h6>
				<p><a href="#">Joss Whedon</a></p>
			</div>
			<div class="sb-it">
				<h6>Senarist: </h6>
				<p><a href="#">Joss Whedon,</a> <a href="#">Stan Lee</a></p>
			</div>
			<div class="sb-it">
				<h6>Oyuncular: </h6>
				<p><a href="#">Robert Downey Jr,</a> <a href="#">Chris Evans,</a> <a href="#">Mark Ruffalo,</a><a href="#"> Scarlett Johansson</a></p>
			</div>
			<div class="sb-it">
				<h6>Tür/Kategori:</h6>
				<p><a href="#">Action, </a> <a href="#"> Sci-Fi,</a> <a href="#">Adventure</a></p>
			</div>
			<div class="sb-it">
				<h6>Çıkış Tarihi:</h6>
				<p>May 1, 2015 (U.S.A)</p>
			</div>
			<div class="sb-it">
				<h6>Süresi:</h6>
				<p>141 min</p>
			</div>
			<div class="sb-it">
				<h6>MMPA Rating:</h6>
				<p>PG-13</p>
			</div>
			<div class="sb-it">
				<h6>Anahtar Kelimeler:</h6>
				<p class="tags">
					<span class="time"><a href="#">superhero</a></span>
					<span class="time"><a href="#">marvel universe</a></span>
					<span class="time"><a href="#">comic</a></span>
					<span class="time"><a href="#">blockbuster</a></span>
					<span class="time"><a href="#">final battle</a></span>
				</p>
			</div>
			<div class="ads">
				<img src="/theme/images/uploads/ads1.png" alt="">
			</div>
		</div>
	</div>
</div>

Frontends/App.Movie.WebUI/Views/Shared/Components/MovieRate/Default.cshtml
<div class="movie-rate">
	<div class="rate">
		<i class="ion-android-star"></i>
		<p>
			<span>8.1</span> /10<br>
			<span class="rv">56 Değerlendirme</span>
		</p>
	</div>
	<div class="rate-star">
		<p>Filmi Değerlendir:  </p>
		<i class="ion-ios-star"></i>
		<i class="ion-ios-star"></i>
		<i class="ion-ios-star"></i>
		<i class="ion-ios-star"></i>
		<i class="ion-ios-star"></i>
		<i class="ion-ios-star"></i>
		<i class="ion-ios-star"></i>
		<i class="ion-ios-star"></i>
		<i class="ion-ios-star-outline"></i>
	</div>
</div>

Frontends/App.Movie.WebUI/Views/Shared/Partials/_PageFooter.cshtml
<footer class="ht-footer">
	<div class="container">
		<div class="flex-parent-ft">
			<div class="flex-child-ft item1">
				<a href="index-2.html"><img class="logo" src="/theme/images/logo1.png" alt=""></a>
				<p>
					Cumhuriyet Caddesi, No:24<br>
					Bostancı, Kadıköy-İstanbul
				</p>
				<p>Bize Ulaşın: <a href="#">(+90) 555 400 67 90</a></p>
			</div>
			<div class="flex-child-ft item2">
				<h4>Hızlı Erişim Linkler</h4>
				<ul>
					<li><a href="#">Hakkımızda</a></li>
					<li><a href="#">Filmler</a></li>
					<li><a href="#">İletişim</a></li>
					<li><a href="#">Forum</a></li>
					<li><a href="#">Blog</a></li>
				</ul>
			</div>
			<div class="flex-child-ft item3">
				<h4>KVKK</h4>
				<ul>
					<li><a href="#">Kullanım Şartları</a></li>
					<li><a href="#">Gizlilik Politikası</a></li>
					<li><a href="#">Güvenlik</a></li>
				</ul>
			</div>
			<div class="flex-child-ft item4">
				<h4>Hesabım</h4>
				<ul>
					<li><a href="#">Profilim</a></li>
					<li><a href="#">İzleme Listem</a></li>
					<li><a href="#">Koleksiyonlarım</a></li>
					<li><a href="#">Kullanıcı Rehberi</a></li>
				</ul>
			</div>
			<div class="flex-child-ft item5">
				<h4>Email Bülteni</h4>
				<p>Son çıkan film ve dizilerden haberdar olmak <br> için hemen abone olun.</p>
				<form action="#">
					<input type="text" placeholder="Email Adresinizi Girin...">
				</form>
				<a href="#" class="btn">Abone Ol <i class="ion-ios-arrow-forward"></i></a>
			</div>
		</div>
	</div>
	<div class="ft-copyright">
		<div class="ft-left">
			<p><a target="_blank" href="https://www.templateshub.net">Templates Hub</a></p>
		</div>
		<div class="backtotop">
			<p><a href="#" id="back-to-top">Yukarıya Dön  <i class="ion-ios-arrow-thin-up"></i></a></p>
		</div>
	</div>
</footer>

Frontends/App.Movie.WebUI/Views/Shared/Partials/_PageHead.cshtml
<title>Movie Api</title>
<meta charset="UTF-8">
<meta name="description" content="">
<meta name="keywords" content="">
<meta name="author" content="">
<link rel="profile" href="#">
<link rel="stylesheet" href='http://fonts.googleapis.com/css?family=Dosis:400,700,500|Nunito:300,400,600' />
<meta name=viewport content="width=device-width, initial-scale=1">
<meta name="format-detection" content="telephone-no">
<link rel="stylesheet" href="/theme/css/plugins.css">
<link rel="stylesheet" href="/theme/css/style.css">

Frontends/App.Movie.WebUI/Views/Shared/Partials/_PageHero.cshtml
<div class="hero common-hero">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="hero-ct">
					<h1> @ViewBag.v1</h1>
					<ul class="breadcumb">
						<li class="active"><a href="#">@ViewBag.v2</a></li>
						<li> <span class="ion-ios-arrow-right"></span> @ViewBag.v3</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>

Frontends/App.Movie.WebUI/Views/Shared/Partials/_PagePreLoading.cshtml
<div id="preloader">
    <img class="logo" src="/theme/images/logo1.png" alt="" width="119" height="58">
    <div id="status">
        <span></span>
        <span></span>
    </div>
</div>

Frontends/App.Movie.WebUI/Views/Shared/Partials/_PageScript.cshtml
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<script src="/theme/js/jquery.js"></script>
<script src="/theme/js/plugins.js"></script>
<script src="/theme/js/plugins2.js"></script>
<script src="/theme/js/custom.js"></script>